[".config/nvim"]
type = "git-repo"
url = "https://github.com/asek-ll/nvim-config.git"
refreshPeriod = "168h"

[".config/alacritty/themes"]
type = "git-repo"
url = "https://github.com/alacritty/alacritty-theme.git"
refreshPeriod = "168h"
